name: Build with PyInstaller

on: [push, pull_request]

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.10'
          spec: 'main.py'
          upload_exe_with_name: 'My executable'
          options: --onefile, --name "My App", --windowed,
