name: PyInstaller Build (Windows)

on:
  push:
    paths:
      - "main.py"
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: "[DEBUG] Print github.ref"
        run: echo "github.ref = ${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Package with PyInstaller
        run: |
          pyinstaller --onefile --windowed main.py

      - name: "[DEBUG] List files in cwd"
        run: |
          tree
          dir dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: dist/main.exe

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: main

      - name: "[DEBUG] List files in cwd"
        run: |
          tree
          ls

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: main.exe
